server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gatewayService_Client
  cloud:
    gateway:
      routes:
        - id: client_loginService
          uri: lb://client_loginService
          predicates:
            - Path=/client_loginService/**
        - id: client_Service
          uri: lb://client_Service
          predicates:
            - Path=/client_Service/**
        - id: couponService
          uri: lb://couponService
          predicates:
            - Path=/couponService/**
        - id: pointService
          uri: lb://pointService
          predicates:
            - Path=/pointService/**
        - id: basket-service # TODO: Change this to basketService
          uri: lb://basket-service # TODO: Change this to basketService
          predicates:
            - Path=/basket-service/** # TODO: Change this to basketService
        - id: recentlyviewedService
          uri: lb://recentlyviewedService
          predicates:
            - Path=/recentlyviewedService/**
        - id: review_cudService
          uri: lb://review_cudService
          predicates:
            - Path=/review_cudService/**
        - id: review_readService
          uri: lb://review_readService
          predicates:
            - Path=/review_readService/**
        - id: product_cudService
          uri: lb://product_cudService
          predicates:
            - Path=/product_cudService/**
        - id: product_readService
          uri: lb://product_readService
          predicates:
            - Path=/product_readService/**
        - id: deliveryService
          uri: lb://deliveryService
          predicates:
            - Path=/deliveryService/**
        - id: orderService
          uri: lb://orderService
          predicates:
            - Path=/orderService/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
