server:
  port: 80

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/




spring:
  application:
    name: gatewayService_Client
  cloud:
    gateway:
      routes:
        - id: client-login-service
          uri: lb://client-login-service
          predicates:
            - Path=/client-login-service/**
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/client-service/**
        - id: coupon-service
          uri: lb://coupon-service
          predicates:
            - Path=/coupon-service/**
        - id: point-service
          uri: lb://point-service
          predicates:
            - Path=/point-service/**
        - id: basket-service
          uri: lb://basket-service
          predicates:
            - Path=/basket-service/**
        - id: recently-viewed-service
          uri: lb://recently-viewed-service
          predicates:
            - Path=/recently-viewed-service/**
        - id: review-cud-service
          uri: lb://review-cud-service
          predicates:
            - Path=/review-cud-service/**
        - id: review-read-service
          uri: lb://review-read-service
          predicates:
            - Path=/review-read-service/**
        - id: product-cudservice
          uri: lb://product-cudservice
          predicates:
            - Path=/product-cudservice/**
        - id: product-read-service
          uri: lb://product-read-service
          predicates:
            - Path=/product-read-service/**
        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/delivery-service/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true


management:
  endpoints:
    web:
    exposure:
      include: "*"
  endpoint:
    health:
    show-details: always